eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_URI:http://localhost:8762/eureka}
    instance:
        prefer-ip-address: true
server:
    port: 8765
spring:
    application:
        name: api-gateway-service
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            routes:
            -   id: sample-service
                predicates:
                - Path=/sample/**
                uri: lb://sample-service/sample
